# Generated by Django 4.1 on 2022-08-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sex',
            new_name='gender',
        ),
    ]
