# Generated by Django 4.1 on 2022-08-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_rename_sex_customer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10, null=True)),
                ('product_name', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(choices=[('N', 'New'), ('U', 'Used')], max_length=1, null=True)),
                ('price', models.FloatField(max_length=15, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.customer')),
            ],
        ),
    ]
