# Generated by Django 4.1 on 2022-08-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='mdb-favicon.ico', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
