# Generated by Django 4.1 on 2022-08-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0007_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
