# Generated by Django 4.1 on 2022-09-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
    ]
