# Generated by Django 4.1 on 2022-09-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0011_rename_message_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='buyers',
            field=models.ManyToManyField(to='Customers.buyer'),
        ),
    ]
