# Generated by Django 4.1 on 2022-09-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0012_customer_buyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='buyers',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='Customers.buyer'),
        ),
    ]
